version: '3.8'
services:
  db:
    image: mysql:5.7
    platform: linux/x86_64
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat_db
      MYSQL_ROOT_USER: root
    ports:
      - "3306:3306"

volumes:
  db-data:
